### PR TITLE
pre-commit-hook support

### LINKED ISSUE #33: Pre-commit integration
Hello !

Great utility, one way to get more adoption would be to provide an integration with pre-commit. 

https://pre-commit.com/

For terraform, for example, I have been using : https://github.com/antonbabenko/pre-commit-terraform

And the modules are always well documented, without worrying about it.

The flow would be : 

1. the chart maintainer installs the pre-commit hook
2. Update the chart's value, etc
3. Commit the change
4. pre-commit kicks in and run frigates, updating the README
5. User is prompted to add the change on the README.

### PR DESCRIPTION
**Pull request by jrottenberg**
Fixes #33.

It was simpler to integrate with cli.py to add a new command : `hook`

`frigate hook` is the entry point of the hook, it discovers all the charts in the project and generate a doc page for each.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by jacobtomlinson** [comment]
ok to test

**Comment by jrottenberg** [comment]
Done, let me know how that looks and if you prefer to have the commits squashed

**Comment by jacobtomlinson** [comment]
This is awesome many thanks! I'll squash on merge.

**Comment by jrottenberg** [comment]
That's great, thank you ! Do you mind cut a tag or a release ? Pre-commit will pick the latest with `pre-commit autoupdate` but we need one, it won't accept a configuration using main, `rev: branch-0.3` works though.

**Comment by jacobtomlinson** [comment]
@jrottenberg `0.4.0` is out

**Pull request merged**
